FROM maven:3.3.3-jdk-8

RUN mkdir -p /usr/local/gaia
WORKDIR /usr/local/gaia

ADD . /usr/local/gaia

# RUN ["mvn","-DuseProxy=true","-DproxyHost=web-proxy.israel.hp.com","-DproxyPort=8080","clean","install"]
RUN ["mvn","clean","install"]
